import Foundation

/// Parses `{NodeName.attr}` template references used in `.mg` input edges.
///
/// Meshroom stores graph edges as strings inside `inputs` dictionaries: the value
/// `"{FeatureExtraction_1.output}"` means "wire the upstream `output` attribute of
/// node `FeatureExtraction_1` into this input".  The braces are part of the syntax;
/// `NodeName` matches `[A-Za-z_][A-Za-z0-9_]*` and `attr` likewise (with optional
/// dotted sub-paths for grouped attributes, e.g. `{CameraInit_1.viewpoints.0}`).
///
/// This type is *only* responsible for parsing the textual form; it does not
/// resolve the reference against a graph (that is a Phase M2 concern).
public struct MGTemplateReference: Hashable, Sendable {
    /// The upstream node name.
    public let nodeName: String
    /// The attribute path on that node.  For a simple reference like
    /// `{Node_1.output}` this is `["output"]`.  Dotted paths in grouped attrs
    /// become multi-element arrays.
    public let attributePath: [String]

    public init(nodeName: String, attributePath: [String]) {
        self.nodeName = nodeName
        self.attributePath = attributePath
    }

    /// Convenience: dotted attribute path, e.g. `"viewpoints.0.path"`.
    public var attributePathString: String {
        attributePath.joined(separator: ".")
    }

    /// Textual round-trip form: `{Node.attr}` or `{Node.attr.sub}`.
    public var rendered: String {
        "{\(nodeName).\(attributePathString)}"
    }

    /// Attempt to parse a single template reference of the form
    /// `{Name.attr}` or `{Name.attr.sub}`.  Returns `nil` if `text` does not
    /// match the template syntax exactly (including surrounding braces and the
    /// dot separator).  Whitespace inside the braces is *not* tolerated, to
    /// match upstream Meshroom behaviour observed in `attribute.asLinkExpr()`.
    public static func parse(_ text: String) -> MGTemplateReference? {
        guard text.hasPrefix("{"), text.hasSuffix("}"), text.count >= 5 else {
            return nil
        }
        let inner = text.dropFirst().dropLast()
        // Reject anything with whitespace or braces inside — those forms aren't
        // generated by Meshroom and we don't want false positives swallowing
        // user-authored strings that happen to start and end with braces.
        if inner.contains(where: { $0.isWhitespace || $0 == "{" || $0 == "}" }) {
            return nil
        }
        let parts = inner.split(separator: ".", omittingEmptySubsequences: false)
        guard parts.count >= 2 else { return nil }
        let nodeName = String(parts[0])
        let attrParts = parts.dropFirst().map(String.init)
        guard isValidIdentifier(nodeName) else { return nil }
        // Attribute components may be numeric indices (list elements) or
        // identifiers.  Empty components are rejected.
        for part in attrParts where part.isEmpty {
            return nil
        }
        return MGTemplateReference(nodeName: nodeName, attributePath: attrParts)
    }

    private static func isValidIdentifier(_ s: String) -> Bool {
        guard let first = s.first else { return false }
        guard first.isLetter || first == "_" else { return false }
        return s.allSatisfy { $0.isLetter || $0.isNumber || $0 == "_" }
    }
}
